### ISSUE TITLE
Including BCA, BBA in IPU Ranklist?

### ISSUE THREAD

**Issue by Animesh-Ghosh** [ankushgarg1998/ipu-ranklist#10]
An issue similar to [this](https://github.com/ankushgarg1998/msit-ranklist/issues/1).

Would it be possible for IPU Ranklist to include all courses (BCA, B.Com, etc)?

**Comment by ankushgarg1998** [comment]
Yes @Animesh-Ghosh Thanks for referencing it.
I've researched a little and studied a few PDFs of BBA and BCA. The format is pretty similar. So (good news) the parser will not require a lot of changes.

As much as I'm excited to integrate these courses in IPU Ranklist, the current priority will be to complete the pre-planned features (like CGPA #2, Profile Section #5 ) and basically bring this to a complete state code-wise.

However, I'll try to finish it up and start working on this as quick as I can.

**Comment by ankushgarg1998** [comment]
Since you've already raised the issue, I'll add the checklist of Tasks here itself:

- [ ] Research PDFs
- [ ] Sit with someone from MSI and understand the course structures and clear your doubts. Also make a list of all the courses to be covered in this Update.
- [ ] Download all the PDFs up till 2015 batch (or up till where there is consistency).
- [ ] Update database or create new to accommodate this new data.
- [ ] Minor changes in Jimmy to fetch from these PDFs and fill up the DB.
- [ ] Front-End Modifications...

**Comment by Animesh-Ghosh** [comment]
Do let me know if I can help in any way. :smiley:

**Comment by Animesh-Ghosh** [comment]
Just saw the BCA ranklist. Looks good (*and* responsive, if you care about that).

👍😎 

PS: I already feel immune to viruses by using the site.

**Comment by ankushgarg1998** [comment]
Hey @Animesh-Ghosh, thanks for reviewing. I'm glad you liked it.

PS: 😆🤣 Great.

**Comment by ankushgarg1998** [comment]
Included BBA as well. Jai mata di.
