### ISSUE TITLE
it's not showing result of batch 2020-2024 of sem 4

### ISSUE THREAD

**Issue by mnnkhndlwl** [ankushgarg1998/ipu-ranklist#133]
results have been declared on ipu website but your site is not showing them

**Comment by ankushgarg1998** [comment]
Hi @mnnkhndlwl 
Which course?

**Comment by mnnkhndlwl** [comment]
btech

**Comment by ankushgarg1998** [comment]
Except for a few re-appear cases, I don't see any pending results for upload.

Can you please share the PDF link?
Your enrollment number also, please.

**Comment by ankushgarg1998** [comment]
@mnnkhndlwl

**Comment by ankushgarg1998** [comment]
@mnnkhndlwl Seems you've closed the issue. Are you able to see the result now?

**Comment by mnnkhndlwl** [comment]
bro I received that results pdf on my college Whatsapp group I couldn't find that on the website sorry to waste your time

**Comment by ankushgarg1998** [comment]
Hey @mnnkhndlwl 
Turns out, that GGSIPU is now uploading new results/datasheets/circulars PDFs on a google sheet (temporary link).

![Screenshot 2022-09-21 at 12 30 31 AM](https://user-images.githubusercontent.com/22600172/191342302-33b728a6-a23e-404c-8b0f-faa270d4b019.png)

I've uploaded the 4th sem result to IPU Ranklist. Thanks for bringing this to my notice.

**Comment by mnnkhndlwl** [comment]
👍😇
