### ISSUE TITLE
RESULT UPDATION OF EVEN SEMSESTER 2022

### ISSUE THREAD

**Issue by superawat** [ankushgarg1998/ipu-ranklist#134]
Please update your webpage with the latest semester results.
I HAVE A PDF OF THE RESULTS ATTACHED:
https://drive.google.com/file/d/1Epd3TITWMPdFNcJHXDPP6dIYHGbnwyj6/view?usp=sharing

**Comment by ankushgarg1998** [comment]
Hey @himanshurawattt 
I'm not able to find this result on the official website of IPU:
http://ggsipu.ac.in/ExamResults/ExamResultsmain.htm

Could you please help with the title of this PDF on the results page? A screenshot would be better.
Thanks.

**Comment by superawat** [comment]
Unfortunately, it is not available on their website, therefore you must wait for the official publishing of results.

**Comment by ankushgarg1998** [comment]
Hey @himanshurawattt 
Turns out, that GGSIPU is now uploading new results/datasheets/circulars PDFs on a google sheet (temporary link).

![image](https://user-images.githubusercontent.com/22600172/191342696-866d345a-eabd-4ebc-bc6f-67fff19e7fa1.png)

I've uploaded the 4th sem result to IPU Ranklist. Thanks for bringing this to my notice.
