### ISSUE TITLE
Issue regarding subject name

### ISSUE THREAD

**Issue by iadi37** [ankushgarg1998/ipu-ranklist#150]
## Hi [ankushgarg1998](https://github.com/ankushgarg1998) 

There are incorrect subject names showing for Btech SEM 2 results for 2021-25 CSE.
-

      Sub: STATISTICS THEORY OF PROBABILITY AND LINEAR PROGRAMMING
      paper id: 099114

 instead of

       Sub: ENGINEERING MECHANICS
       paper id: 027114
       paper code: ES114

&

       Sub: INTRODUCTION TO PROGRAMMING
       paper id: 027108

instead of

       Sub: ELECTRICAL SCIENCE
       paper id: 027108
       paper code: ES108

- At first, it should be 027 instead of 099 as 027 is the CSE code.
- In the second the paper id is the same but I guess University has changed the paper id for the subject and maybe interchanged.

Looking to solve this issue can you please suggest and guide for the same?

**Comment by ankushgarg1998** [comment]
Hi @iadi37 

Welcome to the rabbit hole of GGSIPU's inability to keep a paperID unique, and IPU Ranklist's ignorance in identifying this early.

Right now, IPU Ranklist tries to uniquely identify a subject name corresponding to a paperID.

The following shows the correct entry, from your 2nd sem result.
![Screenshot 2023-05-07 at 3 40 23 PM](https://user-images.githubusercontent.com/22600172/236671307-0e78e1d2-9139-4f71-a9c9-ebe1e57c09da.png)

But GGSIPU has a "different" B.Tech for USICT students, in which they have the same paperID (099114). But a different subject name.
![Screenshot 2023-05-07 at 3 43 45 PM](https://user-images.githubusercontent.com/22600172/236671438-5b3feed4-48b5-4536-992c-bb8591693477.png)

This issue has been noted in #130 & #87 also.
I'll keep your issue open as well.

This is not a straightforward fix, as it requires changes in the data layer, which will bubble up to all the other layers.
But I'll try to fix it soon.

Thanks for raising it. 🙌🏼

**Comment by iadi37** [comment]
Hey @ankushgarg1998, thanks for taking the issue. There is also the same issue in SEM 1 result as well :
```
  sub: FUNDAMENTALS OF COMPUTING
   id: 027111
```

instead of 
 ```  
 sub: APPLIED MATHEMATICS - I
 paper code:   BS111
```
&
```
 sub: FUNDAMENTALS OF COMPUTING LAB 
 id: 027157
```
instead of
```
 sub: ENGINEERING GRAPHICS-I
 paper code: ES157
```

**Comment by ankushgarg1998** [comment]
Recently received another email regarding this issue (BCA Course):

> Actually the marks of c programming is swapped with telecommunication. And the marks of Computers and IT swapped with Physics. and also the subject name physics should be replaced with web technologies as there is no subject physics in new curriculum.

### UPDATE FROM MY END (As of 23rd June 2023):
I'm actively working on a new design that incorporates various schemes of examinations and makes subject names course & scheme specific.
This is part of a larger project that includes a database schema change, and making the data parsing much richer than before.

I'm expecting to complete this before the next results season.

**Comment by realKarthikNair** [comment]
Any update on this? Also, thanks for this amazing work in the form on ipuranklist!

**Comment by ankushgarg1998** [comment]
Hi @realKarthikNair 

Here's an update on the work I've mentioned in my last comment.
I'm almost done with the new parsing layer. I am finishing up some final changes. I've completed the following items:
- [x] Designing & implementing the new DB schemas with mongoose.
- [x] Writing a new parsing layer that auto-chooses parsers and makes it convenient to add new parsers.
- [x] Refactoring all of Jimmy & Jonathan parser's code.
- [x] Plugging these 2 parsers in the parsing layer.
- [x] Testing the new parsing layer for all courses / programmes.

Post these the following items remain:
- [x] Reorganising the pdf file management for various courses. (+ backups)
- [x] Making the parsing layer capable of downloading & book-keeping PDFs.
- [x] Preparing the new prod DB.
- [x] Writing a new back-end layer that serves requests using the new DB.
- [x] Updating the existing front-end layer to leverage the new back-end APIs.

This is taking quite some time because I'm re-writing almost all of the code, and at the same time working towards making this code & website future-proof.
Along-side I'm laying a foundation for the ability to later bring in the some exciting features, which would not have been possible earlier.
Some of those features would be: 
- Students to see which semester results are coming from which page on which PDF files.
- To show which all PDFs from the official GGSIPU website are parsed, and which are in a pending state.

Full details about the release notes from 2023 can be found [here](https://ankushgarg.notion.site/2023-Release-Notes-e53809d033914fdeba13eb5a22d41a26?pvs=4)

**Comment by realKarthikNair** [comment]
Thanks for the update @ankushgarg1998, I really appreciate that..

**Comment by ankushgarg1998** [comment]
Hi Folks.
Posting an update here.
The re-work is taking longer than I'd anticipated.
It is in the final stages now. I'm building the new database, and testing things locally.

As soon as it is production-ready, it'll be deployed by the end of this results season.

**Comment by realKarthikNair** [comment]
@ankushgarg1998 really appreciate the efforts.

**Comment by ankushgarg1998** [comment]
Hi @realKarthikNair @iadi37 

The new version is up and running. ✅ 
I request you to please verify.

(Been waiting for a year to type these words...)
This issue stands closed.

**Comment by iadi37** [comment]
hello @ankushgarg1998 
Yes, now all the subject names have been matched and correct.
Thanks a lot!!  for solving this issue.

**Comment by realKarthikNair** [comment]
@ankushgarg1998 thanks a lot bhaiyya, everything works good now 🥳
