### ISSUE TITLE
Shifts not appearing

### ISSUE THREAD

**Issue by mayanksreal** [ankushgarg1998/ipu-ranklist#169]
Shift option disappeared post new subject code fix update, it displays just the morning shift results. Am I missing something out?

**Comment by ankushgarg1998** [comment]
Hi @mayanksreal 

After the update, all institute codes are treated as separate institutes.
You should see two entries of your college in the institute dropdown. One with morning shift instituteCode and another with evening shift instituteCode.

Please see if this helps.

**Comment by ankushgarg1998** [comment]
To ensure people don't face this issue again, doing the following:

1. Ordered the institute dropdown by abbreviation instead of instituteCodes.
![Screenshot 2024-08-25 at 3 06 47 PM](https://github.com/user-attachments/assets/576648de-841a-44b4-a951-58e0f5b8df7e)

2. Add (morning/evening) shift hints to institutes in the dropdown.
