### ISSUE TITLE
Misread of subject

### ISSUE THREAD

**Issue by saumyanasa** [ankushgarg1998/ipu-ranklist#71]
For sem 4 result of batch 2018-2022, Applied Mathematics 4 has been written as NAST in almost all branches.

**Comment by ankushgarg1998** [comment]
@saumyanasa This because the same paper id (099202) has the name "NUMERICAL ANALYSIS AND STATISTICAL TECHNIQUES" in MECHANICAL AND AUTOMATION ENGINEERING.

I'm seeing a similar case for many subjects, but the subject names are still intuitively similar. 

Currently, I'm not storing branch-specific subject names. So I guess (for now) you're gonna have to make do with this name only. 😅
