### ISSUE TITLE
Some of the semester wise results are showing as "Reappeared", but it's actually not

### ISSUE THREAD

**Issue by covalentbond** [ankushgarg1998/ipu-ranklist#74]
## How to reproduce this issue
Go to https://ipuranklist.com/student/00596303118
Check Sem1 result

![image](https://user-images.githubusercontent.com/53327173/96303240-b44a6a00-1017-11eb-8a8b-86ce7623bc32.png)

**Comment by ankushgarg1998** [comment]
Thanks @covalentbond for reporting this. 
I'll look into it.

**Comment by ankushgarg1998** [comment]
@covalentbond I've found the issue:

The [first-semester result PDF of IT (2018-2022 batch)](http://ggsipu.ac.in/ExamResults/2019/230519/031_IT_1stSEM_2015%20Batch%20Onwards(End%20Term%20Examination,%20December%202018).pdf) had the entire REGULAR result (page 80-205) published again with REAPPEAR as the heading (page 206-331). 🤦🏻‍♂️

You'll be able to see your result on pages 200 & 326 respectively under the heading REGULAR and REAPPEAR.


So I don't think it makes sense to fix it because according to the result PDF, the entire IT batch of IT 2022 reappeared for the first sem exams. 😛
